version: '3.7'
services:
  redis:
    image: "redis:alpine"
    env_file:
      - .env
    command: 'redis-server --requirepass ${REDIS_PASSWORD}'
    ports:
      - '6379:6379'
  worker:
    build: 
      context: .
      dockerfile: jobqueue.Dockerfile
    env_file:
      - .env
    depends_on: 
      - redis
